### ISSUE TITLE
Unhandled Error during Installation

### ISSUE THREAD

**Issue by securebyte** [trigger/trigger#189]
Using /usr/lib/python2.7/dist-packages
    Finished processing dependencies for trigger==1.4.4r2
    Unhandled Error
    Traceback (most recent call last):
      File "setup.py", line 179, in <module>
        _refresh_twisted_plugins()
      File "setup.py", line 178, in _refresh_twisted_plugins
        list(getPlugins(IPlugin))
      File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 209, in getPlugins
        allDropins = getCache(package)
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 167, in getCache
        provider = pluginModule.load()
      File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
        return self.pathEntry.pythonPath.moduleLoader(self.name)
      File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 464, in namedAny
        topLevelPackage = _importAndCheckStack(trialname)
      File "/home/cyberfreak/Downloads/trigger-develop/twisted/plugins/trigger_xmlrpc.py", line 15, in <module>
        from twisted.conch.manhole_tap import makeService as makeConsoleService
    exceptions.ImportError: No module named conch.manhole_tap

**Comment by supertylerc** [comment]
Almost two years old.  Safe to close and reopen at a later date if there's an issue with current Ubuntu LTS and current Trigger?

**Comment by jathanism** [comment]
Yep!
