### ISSUE TITLE
Is there any hints to help how to install it in windows platform?

### ISSUE THREAD

**Issue by mfrank-wang** [trigger/trigger#208]
It doesn't work after being installed. the following errors appears while import modules.

>>> from trigger.netdevices import NetDevices
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\trigger\netdevices\__init__.py", line 38,
in <module>
    from trigger.conf import settings
  File "c:\Python27\lib\site-packages\trigger\conf\__init__.py", line 25, in <mo
dule>
    from . import global_settings
  File "c:\Python27\lib\site-packages\trigger\conf\global_settings.py", line 24,
 in <module>
    TACACSRC = os.getenv('TACACSRC', os.path.join(USER_HOME, '.tacacsrc'))
  File "c:\Python27\lib\ntpath.py", line 64, in join
    result_drive, result_path = splitdrive(path)
  File "c:\Python27\lib\ntpath.py", line 114, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
>>>

**Comment by jathanism** [comment]
Unfortunately we don't officially support Windows right now. Trigger was designed and developed on Linux systems, so we've made a bunch of assumptions about the installed system being on POSIX operating systems (Unix, Linux, Mac OS, etc.).

This particular issue might be solvable by this:

http://stackoverflow.com/questions/4028904/how-to-get-the-home-directory-in-python

If you feel comfortable hacking at the Trigger internals to try to modify the place where `USER_HOME` is set inside of `trigger/conf/global_settings.py` and see if you can make it work, I'll happily provide some guidance!
