### ISSUE TITLE
gnng --csv crashes

### ISSUE THREAD

**Issue by jathanism** [trigger/trigger#250]
This:

```
$ gnng --csv arista-sw1
Traceback (most recent call last):
  File "/Users/jathan/sandbox/virtualenvs/trigger/bin/gnng", line 459, in <module>
    main()
  File "/Users/jathan/sandbox/virtualenvs/trigger/bin/gnng", line 450, in main
    handle_output(all_rows, opts)
  File "/Users/jathan/sandbox/virtualenvs/trigger/bin/gnng", line 366, in handle_output
    writer.writerow([dev] + row)
NameError: global name 'dev' is not defined
```

**Comment by jathanism** [comment]
So does `--sqldb`:

```
$ gnng --sqldb foo.db arista-sw1
DEVICE: arista-sw1
Traceback (most recent call last):
  File "/Users/jathan/sandbox/virtualenvs/trigger/bin/gnng", line 459, in <module>
    main()
  File "/Users/jathan/sandbox/virtualenvs/trigger/bin/gnng", line 450, in main
    handle_output(all_rows, opts)
  File "/Users/jathan/sandbox/virtualenvs/trigger/bin/gnng", line 370, in handle_output
    write_sqldb(opts.sqldb, dev, rows)
NameError: global name 'dev' is not defined
```
