### ISSUE TITLE
gnng not working: 'generator' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by teomcpy** [trigger/trigger#252]
```bash
ubuntu@ubuntu-VirtualBox:~/MyFiles$ netdev -l 172.16.1.2
	Hostname:          172.16.1.2
	Owning Org.:       Cisco Network Dept.
	Owning Team:       Data Center
	OnCall Team:       Data Center

ubuntu@ubuntu-VirtualBox:~/$ssh mihai@172.16.1.2
Password: 

Cisco-R1#

ubuntu@ubuntu-VirtualBox:~/MyFiles$gnng 172.16.1.2
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1087, in connectionLost
    self.factory.clientConnectionLost(self, reason)
  File "/usr/local/lib/python2.7/dist-packages/trigger/twister.py", line 737, in clientConnectionLost
    self.d.callback(self.results)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/trigger/cmds.py", line 476, in parse
    return func(results, device, commands)
  File "/usr/local/lib/python2.7/dist-packages/trigger/cmds.py", line 846, in from_cisco
    alld = data[0]
exceptions.TypeError: 'generator' object has no attribute '__getitem__'
```

**Comment by jathanism** [comment]
Looks like this is related to the new "TextFSM" support in Trigger 1.5.7. Oops.

**Comment by tcuthbert** [comment]
This issue is due the results bucket being filled with both the textfsm generator objects and raw data. We need the parse function to filter out these generator objects.

Leave it with me!

**Comment by tcuthbert** [comment]
This should be fixed by https://github.com/trigger/trigger/pull/255
