### ISSUE TITLE
load_acl not working due to 'global name 'pytz' is not defined'

### ISSUE THREAD

**Issue by teomcpy** [trigger/trigger#259]
```
ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#05$ load_acl cisco100.acl

Logging to /tmp/tmpf3HWH5_load_acl

Traceback (most recent call last):
  File "/usr/local/bin/load_acl", line 773, in <module>
    main()
  File "/usr/local/bin/load_acl", line 651, in main
    work = get_work(opts, args)
  File "/usr/local/bin/load_acl", line 371, in get_work
    (dev_acls, dev.nodeName.split('.')[0], pretty_time(next_ok[dev]))
  File "/usr/local/lib/python2.7/dist-packages/trigger/utils/cli.py", line 176, in pretty_time
    now = datetime.datetime.now(pytz.UTC)
NameError: global name 'pytz' is not defined
```

**Setup:**
```
ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#05$ acl -D 172.16.1.100
172.16.1.100                            10 117 118 119 cisco100.acl
```

**- the cisco100.acl file:**
```
ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#05$ cat cisco100.acl 
access-list 100 deny   ip 10.0.0.0 0.255.255.255 172.16.1.0 0.0.0.255
access-list 100 deny   ip 11.0.0.0 0.255.255.255 172.16.1.0 0.0.0.255
access-list 100 permit ip any any
```

```
ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#05$ gong 172.16.1.100
Connecting to 172.16.1.100.  Use ^X to exit.

Fetching credentials from /home/ubuntu/.tacacsrc

Cisco-R1#
```

- I have the sqlite3 db created and cisco100.acl in the same directory and that is the same directory as in `settings.FIREWALL_DIR` and in the database settings:

```
ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#05$ ls
acls.db  cisco100.acl  cisco101.acl
```

```
ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#05$ sqlite3 acls.db
SQLite version 3.8.11.1 2015-07-29 20:00:57
Enter ".help" for usage hints.
sqlite> .tables
acl_queue  queue    
sqlite> 
```

- the redis configuration:
```
ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#05$ redis-cli
127.0.0.1:6379> 
127.0.0.1:6379> smembers acls:explicit:172.16.1.100
1) "cisco100.acl"
```

- the pytz module is installed:
```
ubuntu@ubuntu-VirtualBox:~/MyFiles/Bonuses/Bonus#05$ python
>>> import pytz
>>> print pytz.__version__
2016.3
```

**Comment by jathanism** [comment]
Thanks for all the context. It looks like it's as simple as the fact that `pytz` is not imported at the top-level of `trigger.utils.cli`.

Looks like this was a regression that was introduced in https://github.com/trigger/trigger/commit/3ce16bac25fc8d2846cd2b4b5112aaabbcbf8dea. 

I'll see if we can get a fix out for this one soon.
