### ISSUE TITLE
GPG: Tacacsrc doesn't accept `old`

### ISSUE THREAD

**Issue by supertylerc** [trigger/trigger#293]
True story:

```python
>>> tacacsrc.convert_tacacsrc()
Converting old tacacsrc to new kind :)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/trigger/.trigger/local/lib/python2.7/site-packages/trigger/tacacsrc.py", line 179, in convert_tacacsrc
    tco = Tacacsrc(old=True)
TypeError: __init__() got an unexpected keyword argument 'old'
>>>
```

See [`Tacacsrc.__init__` here](https://github.com/trigger/trigger/blob/develop/trigger/tacacsrc.py#L226-L227).

**Comment by jathanism** [comment]
**v2.0.0 Update:** Confirmed this bug still exists in the current codebase. The `convert_tacacsrc()` function in `trigger/tacacsrc.py` still passes `old=True` and `old=False` to `Tacacsrc.__init__()`, but that constructor does not accept an `old` parameter (it accepts `tacacsrc_file`, `use_gpg`, and `generate_new`).

This means `convert_tacacsrc()` will raise a `TypeError` on any invocation, making the credential migration tools (`tools/convert_tacacsrc.py` and `tools/tacacsrc2gpg.py`) non-functional. This is a confirmed bug that needs a fix.
