### ISSUE TITLE
Crash when TERM env variable not set

### ISSUE THREAD

**Issue by jathanism** [trigger/trigger#295]
```python
       	  File "/tmp/twisted/python/context.py", line 118, in callWithContext
       	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
       	  File "/tmp/twisted/python/context.py", line 81, in callWithContext
       	    return func(*args,**kw)
       	  File "/tmp/twisted/conch/ssh/service.py", line 44, in packetReceived
       	    return f(packet)
       	  File "/tmp/twisted/conch/ssh/connection.py", line 182, in ssh_CHANNEL_OPEN_CONFIRMATION
       	    log.callWithLogger(channel, channel.channelOpen, specificData)
       	--- <exception caught here> ---
       	  File "/tmp/twisted/python/log.py", line 101, in callWithLogger
       	    return callWithContext({"system": lp}, func, *args, **kw)
       	  File "/tmp/twisted/python/log.py", line 84, in callWithContext
       	    return context.call({ILogContext: newCtx}, func, *args, **kw)
       	  File "/tmp/twisted/python/context.py", line 118, in callWithContext
       	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
       	  File "/tmp/twisted/python/context.py", line 81, in callWithContext
       	    return func(*args,**kw)
       	  File "/tmp/trigger/twister.py", line 1417, in channelOpen
       	    os.environ['TERM'], (80, 24, 0, 0), ''
       	  File "/usr/local/lib/python2.7/UserDict.py", line 23, in __getitem__
       	    raise KeyError(key)
       	exceptions.KeyError: 'TERM'
```

Let's make this `os.getenv('TERM')` instead?

**Comment by johnfzc** [comment]
Unfortunately the solution isn't as simple as that, it blows up in a different way:

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/service.py", line 44, in packetReceived
    return f(packet)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/connection.py", line 182, in ssh_CHANNEL_OPEN_CONFIRMATION
    log.callWithLogger(channel, channel.channelOpen, specificData)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/johnf/tmp/trigger/trigger/twister.py", line 1180, in channelOpen
    self._get_window_size(), '')
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/session.py", line 331, in packRequest_pty_req
    termPacked = common.NS(term)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/common.py", line 26, in NS
    return struct.pack('!L',len(t)) + t
exceptions.TypeError: object of type 'NoneType' has no len()
```

What do you think about this:

```python
        term = os.getenv('TERM')
        if not term:
                term="xterm"
```
