### ISSUE TITLE
trigger won't install with modern setuptools

### ISSUE THREAD

**Issue by tarkatronic** [trigger/trigger#313]
With setuptools==34.3.1 installed, when running `pip install trigger`, I get the following:

```python
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/jwilhelm/.virtualenvs/trigger-py2/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/Users/jwilhelm/.virtualenvs/trigger-py2/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/Users/jwilhelm/.virtualenvs/trigger-py2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/Users/jwilhelm/.virtualenvs/trigger-py2/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
        MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
    TypeError: __call__() takes exactly 2 arguments (1 given)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mx/gn154d8j3254p213qkhd6n3mlnym4m/T/pip-build-WU_p8B/pyparsing/
```

I was able to work around this by first running `pip install setuptools==0.9.8`.

**Comment by tarkatronic** [comment]
It looks like you actually can use an even more modern version of setuptools. A simple fix for now would be to add a requires of: `setuptools <= 33.1.1`

**Comment by jathanism** [comment]
Looks like it may actually be an issue w/ pyparsing and not Trigger. See: https://github.com/pypa/setuptools/issues/969
