### ISSUE TITLE
Load_acl uncaught exception when MySQL is unreachable

### ISSUE THREAD

**Issue by jathanism** [trigger/trigger#60]
`load_acl` crashes when MySQL is unreachable. Let's make it exit gracefully.

Exception 1: 

```
Traceback (most recent call last): 
 File "/usr/local/bin/load_acl", line 58, in <module> 
   queue = Queue(verbose=False) 
 File "/usr/local/packages/python-modules-2.0/lib/python/site-packages/trigger/acl/queue.py", line 42, in __init__ 
   self.dbconn = settings.get_firewall_db_conn() 
 File "/etc/trigger_settings.py", line 183, in get_firewall_db_conn 
   port=DATABASE_PORT, user=DATABASE_USER, passwd=DATABASE_PASSWORD) 
 File "/usr/local/packages/python-modules-2.0/lib/python/site-packages/MySQLdb/__init__.py", line 81, in Connect 
   return Connection(*args, **kwargs) 
 File "/usr/local/packages/python-modules-2.0/lib/python/site-packages/MySQLdb/connections.py", line 188, in __init__ 
   super(Connection, self).__init__(*args, **kwargs2) 
_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)") 
```

Exception 2: 

```
Traceback (most recent call last): 
 File "/usr/local/bin/load_acl", line 58, in <module> 
   queue = Queue(verbose=False) 
 File "/usr/local/packages/python-modules-2.0/lib/python/site-packages/trigger/acl/queue.py", line 42, in __init__ 
   self.dbconn = settings.get_firewall_db_conn() 
 File "/etc/trigger_settings.py", line 179, in get_firewall_db_conn 
   port=DATABASE_PORT, user=DATABASE_USER, passwd=DATABASE_PASSWORD) 
 File "/usr/local/packages/python-modules-2.0/lib/python/site-packages/MySQLdb/__init__.py", line 81, in Connect 
   return Connection(*args, **kwargs) 
 File "/usr/local/packages/python-modules-2.0/lib/python/site-packages/MySQLdb/connections.py", line 188, in __init__ 
   super(Connection, self).__init__(*args, **kwargs2) 
_mysql_exceptions.OperationalError: (2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 104")
```

**Comment by abhijo89-uc** [comment]
Why Can't be recreate the connection and try ?

**Comment by jathanism** [comment]
The client is very simple unfortunately. Contributions welcome!
