### ISSUE TITLE
Tacacsrc should exit gracefully when it can't read the .tacacsrc

### ISSUE THREAD

**Issue by jathanism** [trigger/trigger#78]
deferred = execute_junoscript(dev, commands, incremental=inc, with_errors=True, timeout=TIMEOUT)
  File "/usr/local/lib/python/site-packages/trigger/twister.py", line 428, in execute_junoscript
    channel_class, prompt_pattern, method)
  File "/usr/local/lib/python/site-packages/trigger/twister.py", line 382, in execute_generic_ssh
    device, connection_class)
  File "/usr/local/lib/python/site-packages/trigger/twister.py", line 658, in __init__
    TriggerClientFactory.__init__(self, deferred, creds)
  File "/usr/local/lib/python/site-packages/trigger/twister.py", line 575, in __init__
    self.creds = tacacsrc.validate_credentials(creds)
  File "/usr/local/lib/python/site-packages/trigger/tacacsrc.py", line 156, in validate_credentials
    tcrc = Tacacsrc()
  File "/usr/local/lib/python/site-packages/trigger/tacacsrc.py", line 286, in __init__
    self.write()
  File "/usr/local/lib/python/site-packages/trigger/tacacsrc.py", line 447, in write
    return self._write_old()
  File "/usr/local/lib/python/site-packages/trigger/tacacsrc.py", line 404, in _write_old
    for realm, (uname, pwd, _) in self.creds.iteritems():
ValueError: need more than 0 values to unpack

This only happens in SSH channels when .tacacsrc can't be found/read. When using go or other CLI tools it typically prompts the end-user.

**Comment by jathanism** [comment]
This seems to actually only happen when it's trying to write empty credentials. For example:

```python
12:20:21 In [10]: tcrc.creds['dropbox'] = {}

12:20:34 In [11]: tcrc.write()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-1c95899b86b4> in <module>()
----> 1 tcrc.write()

/Users/jathan/sandbox/trigger/tacacsrc.pyc in write(self)
    463             return self._write_new()
    464
--> 465         return self._write_old()
    466
    467     def _update_perms(self):

/Users/jathan/sandbox/trigger/tacacsrc.pyc in _write_old(self)
    420             (self.__module__, strftime('%Y-%m-%d %H:%M:%S %Z', localtime()))]
    421
--> 422         for realm, (uname, pwd, _) in self.creds.iteritems():
    423             #log.msg('encrypting %r' % ((uname, pwd),), debug=True)
    424             out.append('%s_uname_ = %s' % (realm, self._encrypt_old(uname)))

ValueError: need more than 0 values to unpack
```

This is working as intended.
